### ISSUE TITLE
Refactor modal

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10095]
The current implementation of our modal has quite a few downsides, such as holding logic that it is not supposed to hold (e.g. password enforcement rules) and being limited to one active modal.

### To-Dos

- [ ] Decouple modal from store and use a wrapper component that handles the modals (e.g. via event bus)
- [ ] Allow stacking multiple modals that will be processed in a queue
- [x] Remove custom logic such as password enforcement rules and use dedicated components instead
- [x] Clean up modal implementations where the logic is currently spread all over the place. These things should be file actions that create a modal using a custom component. Logic can then sit either in the file action, or in the component (see e.g. how it's done in https://github.com/owncloud/web/pull/10076).
  - [x] Quota modal
  - [x] Create user modal
  - [x] Edit user login modal
  - [x] Add/remove users to/from groups modal
  - [x] Create group modal
  - [x] Create shortcut modal
  - [x] Readme content modal
- [ ] Establish pattern for onConfirm/onCancel handling
  - [ ] Establish clean pattern to replace the buttons while still leveraging the onConfirm handling
  - [ ] Close modal automatically when onConfirm successfully returns/resolves
  - [ ] Show progress indication while promise has not returned (and disable button)
