### ISSUE TITLE
Protected Spaces

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#10105]
# Description

## User Stories

* > As a user I want that only selected Spaces are restricted by higher security settings, so that efficiency of others is not unnecessarily impaired.

## Value

- preserve efficiency while not affecting security

## Acceptance Criteria

- To Spaces a set of settings can be applied and will be called "Protected Spaces"
- A set of settings can be renamed by the Admin
- Protected Spaces can be filtered in the Space overview via click on the toggle filter chip "Protected"
- Protected Spaces are highlighted with a special color and and Icon 
The following settings can be enabled / disabled:
  - Enable/Disable: Access requires MFA
  - Enable/Disable: sync data with Desktop and mobile clients (access only via the Web UI, clients don't know about any protected Space)
  - Enable/Disable: sharing
    - If Enabled: Standard max. expiration date [Days] (users can set less)
  - Enable/Disable: Enforce Password for links
  - Enable/Disable: Delete files after [Years][Days]
  - Enable/Disable: Inactivity logout (Instance default)
  - Enable/Disable: Disable download options
  - Enable/Disable: Disable Copy/Move from or to other Spaces or Personal 

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues
