### ISSUE TITLE
Sharing NG

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10418]
Sharing NG is the next gen sharing API in oCIS that deprecates the old OCS API. The purpose of this issue is to keep track of all the things that need to be done in Web to fully make the switch to the new API.

### Basic functionality

- [x] Implement sharing NG for listing shares (https://github.com/owncloud/web/pull/10392)
- [x] Implement sharing NG for sidebar share loading & CRUD (https://github.com/owncloud/web/pull/10433)
- [ ] Make proper use of permissions (https://github.com/owncloud/web/issues/10770)
- [ ] Denies (currently blocked by the server)

### Bugs

- [x] Password modal is missing when passwords are enforced for links and an internal link is being updated to the type `edit`. (https://github.com/owncloud/web/pull/10690)
- [x] Banned password error message isn't captalized and therefore can't be translated (https://github.com/owncloud/web/pull/10685)
- [x] The role display names and descriptions are not as they were before (server issue)
- [x] Some role display names and descriptions are not being translated yet, they need to be added to the additional translations for Transifex to pick them up. (https://github.com/owncloud/web/pull/10695)
- [x] Share date is missing (https://github.com/owncloud/web/issues/10778)
- [x] rework sharing indicators since there is no more resharing (https://github.com/owncloud/web/pull/10759)

### Hacks to be removed when server is ready

- [x] Tokeninfo for public links (see issue https://github.com/owncloud/web/issues/10689)
- [x] `hidden` property (https://github.com/owncloud/web/issues/10768)
- [x] Suggested roles (https://github.com/owncloud/web/pull/10774)
- [x] Space root endpoint for space roots (https://github.com/owncloud/web/pull/10745)
- [x] Role icon map (https://github.com/owncloud/web/issues/10777)

### Tests

- [x] Add unit tests (https://github.com/owncloud/web/pull/10704 & https://github.com/owncloud/web/pull/10710)
- [x] Adjust e2e and acceptance test role selectors and remove human readable id mappings (https://github.com/owncloud/web/pull/10684)

### Checks

- [ ] Check that federated sharing (OCM) still works (currently blocked by https://github.com/owncloud/ocis/issues/8564)
- [ ] Check that `fullShareOwnerPaths` still work as expected
- [x] Check if we still need to distinguish between space and non-space share types. Or more radical: can we remove the concept of share types as a whole? (https://github.com/owncloud/web/pull/10701)
- [x] Check that the capabilities for passwords are respected correctly
- [x] Check if https://github.com/owncloud/web/blob/master/packages/web-app-files/src/components/SideBar/Shares/SharesPanel.vue#L50 can be removed (https://github.com/owncloud/web/pull/10696)
- [x] Check if space member loading and setting can be simplified (https://github.com/owncloud/web/pull/10699)

### Clean up

- [x] Remove `aggregateResourceShares` (https://github.com/owncloud/web/pull/10426)
- [x] Remove `ShareStatus` and `status` property from  the `ShareResource` interface (https://github.com/owncloud/web/pull/10421)
- [x] Remove `share` property from the `ShareResource` interface (https://github.com/owncloud/web/pull/10426)
- [x] Remove re-sharing logic
- [x] Remove `SharePermission` and `SharePermissions` (https://github.com/owncloud/web/pull/10694)
- [ ] Remove `SharePermissionBit` (https://github.com/owncloud/web/issues/10772 - blocked by https://github.com/owncloud/ocis/issues/8740 and https://github.com/owncloud/ocis/issues/8741)
- [x] Remove all `ShareRoles` and rename `ShareRoleNG` to `ShareRole` (https://github.com/owncloud/web/pull/10682)
- [x] Make sure the OCS sharing API isn't being used anymore and remove SDK dependency (https://github.com/owncloud/web/pull/10679)
- [x] Merge `share/functions.ts` and `share/functionsNG.ts` in `web-client` (https://github.com/owncloud/web/pull/10683)

### Open questions

- [x] ~Will there be a share date? (https://github.com/owncloud/ocis/issues/8749)~
- [ ] How are role names and descriptions being translated in the future?
- [ ] Will there be adequate roles and permissions for the different `type`'s of a link?
- [ ] Will the dav property `PublicLinkPermission` on public spaces be translated to `type`? (https://github.com/owncloud/ocis/issues/8740)
- [ ] Will the `default_permissions` in the capabilities be translated to `type`? (https://github.com/owncloud/ocis/issues/8741)
- [x] ~Is it possible to get an `icon` property for share roles? (https://github.com/owncloud/ocis/issues/8844)~
- [x] ~What about denied shares, do they work yet? -> no role for this yet~
- [ ] What about CERN specific features (mainly notification)?

**Comment by JammingBen** [comment]
I'm closing here since most of the stuff is done. The rest has been converted into single issues meanwhile.
