### ISSUE TITLE
Properly publish web-client package

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#10773]
The `web-client` package is supposed to be the successor of the deprecated `owncloud-sdk`. It contains abstraction layers for all currently used APIs (webdav, graph and a few ocs endpoints).

We already published the package a while ago, but it's not up to date anymore and we need to do a little clean up to get it out again.

### To-Dos

- [x] Integrate the webdav implementation in the [exported client](https://github.com/owncloud/web/blob/master/packages/web-client/src/index.ts#L21)
- [x] Clarify: the exported client takes arguments such as the computed user, access token etc. Can we expect users of this package to provide information in such format?
- [x] Publish a latest release of the package
- [x] Implement a proper build process/pipeline (?)
- [x] Add docs for the `web-client` package
- [x] Add a readme file for the `web-client` package
- [x] Decide on how we want to handle releases in the future (couple with Web releases or independent) -> outcome: we couple the release of the package to Web releases. Meaning e.g. when Web v9 gets released, we release web-client v9 as well.
