### ISSUE TITLE
[Research] Password Protected Folders

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#11789]
# Description

## User Stories

* > As a user I want to restrict access to a folder via a password so that users can't access the folder without the pw.

## Value

- Gamification (eg. in educational usecases)
- Reduce insider thread
- Data Loss Prevention

## Acceptance Criteria

- New Context menu option "Restrict with password", icon: https://remixicon.com/icon/lock-password-line
- If set, everyone needs to enter the password to enter this folder.
- restricted folders can be nested 
- Click on option, opens dialog:
  - Title: **Restrict with password**
  - Copy text: `Restrict access to "Folder XY" with a password. It will only be available via browser and removed from all other devices.`
  - Context helper: **Who can edit the password?** Anyone who can edit this folder can change or remove the password. 
  - Password Field: Same as for links. Follows the PW policy if enabled
  - Buttons: **Cancel**, **Save**
- If the restriction is set, the folder is not synced with any other client.
- If the restriction is set, the context menu actions are
  - "Edit password restriction", same icon as initially
  - "Remove password restriction", icon: https://remixicon.com/icon/lock-unlock-line
- Set, edit and remove the pw is only possible for users with editing

## Definition of ready
- [ ] Everybody needs to understand the value written in the user story
- [ ] Acceptance criteria have to be defined
- [ ] All dependencies of the user story need to be identified
- [ ] Feature should be seen from an end user perspective
- [ ] Story has to be estimated
- [ ] Story points need to be less than 20

## Definition of done
- Functional requirements
  - [ ] Functionality described in the user story works
  - [ ] Acceptance criteria are fulfilled
- Quality
  - [ ] Code review happened
  - [ ] CI is green (that includes new and existing automated tests)
  - [ ] Critical code received unit tests by the developer
- Non-functional requirements
  - [ ] No sonar cloud issues

**Comment by tbsbdr** [comment]
needs research how to technically solve this issue

**Comment by LukasHirt** [comment]
@kobergj since we have an action plan in https://github.com/owncloud/web/issues/12039 I guess we can close this issue?
