### ISSUE TITLE
More tests for collaborators expiration date

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/web#3132]
Follow up on #3086

Needs to be implemented:

- [x] Change of existing expiration date https://github.com/owncloud/phoenix/pull/3157 #3199 
- [x] Enforced expiration date https://github.com/owncloud/phoenix/pull/3241 #3159
- [x] Group expiration date #3157
- [x] Editing user and group shares when both have different default/enforced expiration dates - bug see #3174
- [x] Expiration date gets displayed (unit test should be enough)

**Comment by individual-it** [comment]
@kiranparajuli589 @jasson99 how much of that issue is left to do?

**Comment by kiranparajuli589** [comment]
> * [ ]  Editing user and group when both have different default/enforced expiration dates
@individual-it @LukasHirt @jasson99 
Is this really editing user/group or editing user/group shares??

**Comment by kulmann** [comment]
> > * [ ]   Editing user and group when both have different default/enforced expiration dates
> 
> @individual-it @LukasHirt @jasson99
> Is this really editing user/group or editing user/group shares??

This is editing of user-shares and group-shares. Expiration dates are defined separately for the two share types (but in the same manner for both).

We don't have user and group editing in Phoenix, yet. ;-)

**Comment by individual-it** [comment]
@LukasHirt what do you mean by the unit tests in `Expiration date gets displayed (unit test should be enough)`? AFAIK there are no unit tests in phoenix

**Comment by LukasHirt** [comment]
@individual-it Yeah, unit tests are not yet in place but we want to bring them soon (#2026). For now, I'd say we can postpone that one scenario. My main reason for doing this as a unit test is that acceptance tests would need to do some gymnastics to really test it reliably since the displayed expiration date changes depending on the time of the day. So it doesn't seem worth the effort to me. Unit tests should be perfectly enough IMHO.

**Comment by pascalwengerter** [comment]
Just fixed the selectors for expiration dates in the acceptance tests the other day so closing this as fixed :) we'll perhaps move some of it to unit tests soon, but let's open a new ticket for that when it gets relevant
