### ISSUE TITLE
list of helpers for unit testing

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#5236]
#### packages/web-app-files/src/:
- [x] resources/
- [x] share/
- [x] user / 
- [x] helpers/batchActions.js (doesn't contain any logic to test)
- [x] helpers/path.js
- [x] helpers/resources.js (#5774)
- [x] helpers/shareTypes.js (doesn't contain any logic to test)
- [x] helpers/textUtils.js (#5772 )
- [x] helpers/collaboratorRolesDefinition.js (#5544)
- [x] helpers/permissions.js
- [x] helpers/route.js (#5775)
- [x] helpers/statusIndicators.js (#5771)
- [ ] helpers/collaborators.js  (#5653)
- [x] helpers/publicLinkRolesDefinition.js (TODO: #5779) (#5791)
- [x] helpers/shareStatus.js (doesn't contain any logic to test)
- [ ] helpers/store.js
- [ ] mixins.js (only some of the units are tested)  => Please reach out to @kulmann before starting tests on mixins - the web team wants to get rid of them in the near future so we will be picky which ones are important enough
- [ ] quickAction.js
- [x] mixins/collaborators.js
- [x] mixins/resources.js  (#5642 )
- [ ] More mixins => Please reach out to @kulmann before starting tests on mixins - the web team wants to get rid of them in the near future so we will be picky which ones are important enough
  - [ ] accessibleBreadcrumb.js (involves `document` in method implementations, which is always undefined while testing separately. suggestion needed )
  - [ ] actions
    - [ ] acceptShare.js
    - [ ] copy.js
    - [ ] createPublicLink.js
    - [ ] declineShare.js
    - [ ] delete.js
    - [ ] download.js
    - [ ] favorite.js
    - [ ] fetch.js
    - [ ] move.js
    - [ ] navigate.js
    - [ ] rename.js
    - [ ] restore.js
    - [ ] showActions.js
    - [ ] showDetails.js
    - [ ] showShares.js
  - [x] collaborators.js
  - [ ] deleteResources.js
  - [ ] ileActions.js
  - [ ] filesListFilter.js
  - [ ] filesListPagination.js
  - [ ] filesListPositioning.js
  - [ ] filesListScrolling.js
  - [x] resources.js #5642 
  - [ ] routes.js (#5775)
  - [ ] sidebar
      - [ ] destroySideBar.js
      - [ ] mountSideBar.js

#### packages/web-runtime/src/helpers/:
- [x] config.js
- [x] resource.js
- [x] theme.js

### Motivation
- https://github.com/owncloud/web/issues/5217

**Comment by individual-it** [comment]
blocked waiting for reviews of @kulmann @pascalwengerter

**Comment by phil-davis** [comment]
@kiranparajuli589 @individual-it is this still blocked, or is it done, or?

**Comment by kiranparajuli589** [comment]
blockers were resolved. we'd not worked in this for a while. the list is also outdated. developers are adding the unit tests now, so we can close this one.
