### ISSUE TITLE
list of views for unit testing

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/web#5237]
#### packages/web-app-files/src/views/:
- [x] Favorites.vue  #5345
- [x] FilesDrop.vue #5680 
- [x] LocationPicker.vue #5697 
- [x] Personal.vue (there are some duplication for setup inside the tests, we can refactor this) (#5588)
- [x] PrivateLink.vue (TODO: #5750) (#5755)
- [ ] PublicFiles.vue wip @kiranparajuli589 #5722 #6181
- [x] PublicLink.vue #5749 #5756 
- [x] SharedViaLink.vue (TODO: #5751) (#5778)
- [x] SharedWithMe.vue #5814 (https://github.com/owncloud/web/pull/5814/commits/90e37cc145655ef362733d3177c1fddbbe8037e7)
- [x] SharedWithOthers.vue wip @kiranparajuli589 #5722 #6175
- [x] Trashbin.vue wip @kiranparajuli589 #5722 #6174

### Motivation
- https://github.com/owncloud/web/issues/5217

**Comment by individual-it** [comment]
blocked waiting for reviews of @kulmann @pascalwengerter

**Comment by phil-davis** [comment]
@kiranparajuli589 is this done, or can progress, or?

**Comment by kiranparajuli589** [comment]
this is done and can be closed.
