### ISSUE TITLE
Release 5.1.0

### ISSUE THREAD

**Issue by kulmann** [owncloud/web#6452]
## Release checklist
- [x] pin release issue @kulmann 
- [x] prepare release rc: @kulmann
  - [x] create a branch `release-5.1.0` @kulmann
  - [x] update the version in `packages/web-integration-oc10/appinfo/info.xml` @kulmann
  - [x] update the version in `package.json` @kulmann
  - [x] update the version in `sonar-project.properties` @kulmann 
  - [x] move changelog/unreleased/* to changelog/VERSION_YYYY-MM-DD @kulmann
  - [x] update the ocis commit id in `.drone.env` to the most recent one from ocis master (let's see how it goes) @kulmann
  - [x] commit, push and create **draft** PR (#...) for this branch @kulmann
- [x] create pre release tag `v5.1.0-rc` from the release branch @kulmann 
- [x] smoke test 
  - [x] against oCIS @lookacat 
  - [ ] against oc10 standalone
  - [x] against oc10 as app installation @lookacat 
  - [ ] against oCIS wopi example / app provider
  - [x] against oc10 with OnlyOffice app installed @kulmann @xoxys 
- ~~ if needed, fix issues or write down known issues ~~
- [x] update `YYYY-MM-DD` to current date in `changelog/VERSION_YYYY-MM-DD`
- [x] Make sure translations are up to date by updating them in Transifex and restarting translation sync job https://drone.owncloud.com/owncloud/translation-sync/
- repeat above steps if a new rc is needed
- [x] Run translations sync job once again
- [x] go to the releases section and click `Draft a new Release`. Use `v5.1.0` as a tag (the v prefix is important) and `5.1.0` as name and publish it
- [x] ping in internal #btr channel to create a signed release and ask them to upload it to a) the github release page, b) marketplace.owncloud.com, c) portal.owncloud.com, d) customer.owncloud.com
- [ ] merge release branch https://github.com/owncloud/web/pull/6451 back to master (CI must be green)

**Comment by lookacat** [comment]
#  SmokeTest  against ocis
branch: v5.0.0-rc

### Case 1: admin share folder(with file) to marie:

Admin:
- [ ]  upload big file 30gb - very slow 
- [ ]  upload big file 10gb - very slow
- [ ] upload folder with 848 files. 
- [ ] Check pagination, count items per page. 
- [ ] upload folder(drag folder) "folder_to_share" with file.pdf Bug: https://github.com/owncloud/web/issues/6426
- [ ] share folder "folder_to_share" to marie with edit right

Marie:
- [ ] accept "folder_to_share"
    ❌ - when you try to rename file before accept you get 404 Error. Which I think is right. Do we need button "rename"? 
![image](https://user-images.githubusercontent.com/84779829/153603546-db0ffdb1-07a3-4e25-97d4-8512460e0873.png)


- [ ] rename "folder_to_share" (?admin don't see)
- [ ] upload new file "file.txt" to "folder_to_share" (admin see new file)
- [ ] open pdf file
- [ ] rename file.pdf (use rigth click) (admin see that file changed name)
- [ ] try to move "folder_to_share" to "/" (501 not implement)
- [ ] copy "folder_to_share" to "/"

Admin:
- [ ] add new file.jpeg to "folder_to_share" (marie can see file without access)
- [ ] add file format drawio(marie can open in Draw.io and can edit) 
- [ ] move file.pdf to "/" (marie can not see file.pdf)
- [ ] add new "file.txt" create new version. (marie can see new version)
- [ ] open txt file in markdown-editor. Change and save.
Marie:
- [ ] can download both versions (!error 501)
- [ ] restore old version

Admin:
- [ ] change share "folder_to_share" from "edit" to "viewer" (marie cannot rename/move/delete/download file in folder and cannot create new document in the folder)

Marie:
- [ ] decline folder 

Admin:
- [ ] delete folder "folder_to_share" (marie: folder Shares empty)

## Case 2: admin share file to marie:

Admin:
- [ ] upload file.jpeg
- [ ] share file.jpeg to marie with rigth viewer (use main menu. find marie by email marie@example.org)

Marie:
- [ ] accept file (marie can open/download/copy file but cannot delete/move/rename)
- [ ] copy file to "/"
- [ ] open file in Mediaviewer
- [ ] download file

Admin:
- [ ] change share "file.jpeg" from "viewer" to "edit"(marie can open/download/copy/rename file)

Marie:
- [ ] rename file (admin don't see)

Admin:
- [ ] unshare "file.jpeg" (marie cannot see "file.jpeg" in Shares/Shared for me but see the copied file)

## Case 3: admin create public links to folder

Admin:
- [ ] create folder "for upload"
- [ ] add link with name "to_upload" with role "Uploader" with pass and expiration date
- [ ] open link (can only upload)
- [ ] upload file (admin can see new file)
- [ ] refresh page(page is empty)
- [ ] change share "for upload" from "Uploader" to "edit" Bug: https://github.com/owncloud/web/issues/6429
- [ ] open old link (it work as upload)
- [ ] open new link (can open/download/copy/rename/move files)
- [ ] admin add new file to "for upload"
- [ ] refresh link (file exist)
- [ ] admin change pass (refresh link)

## Case 4: admin create link to file

Admin:
- [ ] create file png
- [ ] add link with main menu
- [ ] open link(can open, download, see) in the incognito tab

- [ ] change link, add pass
- [ ] refresh page (input pass)
- [ ] delete link
- [ ] refresh page (resource not found)
- [ ] delete file
- [ ] restore
- [ ] delete
- [ ] Empty trash

## Case 5: create new user:

Admin:
- [ ] create new account "tom"

Tom:
- [ ] go to account https://github.com/owncloud/web/issues/6430
- [ ] change language

Admin:
- [ ] block user (Login Error access denied)
- [ ] delete user (Logon failed)
- [ ] logout



## Findings:

**Comment by lookacat** [comment]
## Smoke test v5.0.0-rc against oc10 app

- ❓ as gunter - upload arch/mips folder from linux kernel (1945 files)
        - ❓ drag and drop folder upload completely broken 👎 error `the server responded with a status of 403 (Forbidden)`
        - via folder upload button works
	- progress bar is not sticky
	- expanding the upload progress section slows down browser & upload time significantly
- ❓ as gunter - share the folder to alice as viewer
        - sharing is not possible before the upload finished (user invite field doesn't stay focussed) 
        - ❓ for reaching the invite form field one needs to tab through the whole file list until the sidebar is reached (focus should be set to sidebar or sidebar panel instead, depending on a11y needs)
- ❓ as alice - share is already accepted. declining and accepting again works as expected (buttons in shared with me table, batch action, right sidebar)
- ❓ as alice - try do delete file from shared folder
        - individual delete action not visible, good
        - batch delete action not visible, good
        - context menu action not visible, good
- ❓ as alice - try to add file
        - not possible (which is expected) but drag & drop upload didn't handle it. opened file in new tab instead.
- ❓ as alice - copy 16 folders from share to home
	- no visible feedback that it's in progress
	- UI still weirdly usable, ended up in an active upload drop zone. Needed a page reload to be usable again.
	- folder listing after copy shows `?` as folder size on some of the copied folders.
- ❓ as gunter - add new file to share
- ❓ as alice - receive new file in existing share
- ❓ as gunter - unshare folder from shared with others 
- ❓ as alice - try to revisit old share
	- shows `resource not found` upon page reload, good
	- going back to `All files` or `Shared with me` doesn't list the share anymore, good
- ❓ as gunter - share folder with alice again, but as editor
        - setting and removing an expiration date work as expected, good
- ❓ as alice - rename file
	- via right sidebar, works, good
	- via context menu, works, good
- ❓ as gunter - add file
- ❓ as alice - delete file
	- via right sidebar, works, good
	- via context menu, works, good
	- via batch action, works, good
- ❓ as alice - create public link on any folder
- ❓ as alice delete file and recover it
- ❓ as alice create version of textfile
- ❓ as alice view version history of text file
- ❓ as alice download newest version of text file
- ❓ download older version of text file
- ❓ restore older version of text file
- ❓ as alice - upload avatar in classic UI
- ❓ as alice, move a file into subfolder via drag and drop
- ❓ as alice, move multiple files & folders into subfolder via drag and drop
- ❓ as alice, navigate into a folder, open right sidebar without selection, share current folder with gunter

### Findings from old smoke testing:
- ❓ avatar in top bar doesn't have correct aspect ratio, see screenshot (solved)
<img width="163" alt="Screenshot 2022-02-11 at 15 51 55" src="https://user-images.githubusercontent.com/3532843/153613682-ee2f63d8-ba96-4865-a3ad-6ead51bbe731.png">

### Findings from new smoke testing:

**Comment by xoxys** [comment]
@kulmann and I did a quick test of OnlyOffice + oC 10 + oC Web. Can confirm it works.
