### ISSUE TITLE
E2e tests. implement tests for searching

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/web#7395]
need to implement:

- [x] search by personal space. https://github.com/owncloud/web/pull/7583
- [x] search by shares jail 
- [x] search by project space after is fixed
- [x]  `cannot be implemented` see #7849 search for public (public link) (after this issue is fixed https://github.com/owncloud/web/issues/7603)

cases:
- [x] searching folder/subfolder, https://github.com/owncloud/web/pull/7583
- [x] files  https://github.com/owncloud/web/pull/7583
- [ ] name of project space. after https://github.com/owncloud/ocis/issues/4506 is fixed
- [x] different register. Should be case independent. (You have folder "FolDer" and should find it by "foldeR" ) https://github.com/owncloud/web/pull/7583
- [x] ~~pending or declined share~~ (API tests added, no need for e2e - for context https://github.com/owncloud/web/issues/7395#issuecomment-1240362673)
- [x] ~~deleted files.~~  (API tests added, no need for e2e - for context https://github.com/owncloud/web/issues/7395#issuecomment-1240362673)
- [x] hidden files https://github.com/owncloud/web/pull/7583
- [x] ~~check limit- 5 and more~~ checked in api tests

**Comment by SwikritiT** [comment]
@ScharfViktor for character limit of search length ` FRONTEND_SEARCH_MIN_LENGTH` this variable only works while searching for share. Is this the expected behavior for now?
 I couldn't use global search to search for the project spaces. Look at the given video

https://user-images.githubusercontent.com/41103328/188127572-4055f72e-9b72-4a90-9252-f39bd9d75ded.mp4

Also, I found a weird behavior while searching for a folder and navigating to it through the displayed search list

1. As user `Einstein` create folders like `folder`, `newfolder`, `new-folder` 
2. Now search for `folder`
3. Now click on `folder`  and navigate to the folder through search list like so

https://user-images.githubusercontent.com/41103328/188128128-9de34a5c-0eb7-4480-b7c6-1949b693c2b6.mp4

4. Now make Einstein the  `Space Admin`  and repeat the same process of searching and navigating to folder through search list


https://user-images.githubusercontent.com/41103328/188128437-c4a68a1a-7553-456d-b3ba-21c49bdb2c96.mp4

Now `Resource not found ` is shown and the `upload` and `new` buttons are disabled.

Seems like a bug

**Comment by ScharfViktor** [comment]
There is existing bug: https://github.com/owncloud/web/issues/7391
we are waiting fixing from backend side

**Comment by ScharfViktor** [comment]
I tested it (works correct for project and personal space).try test again after merging https://github.com/owncloud/ocis/pull/4485

**Comment by ScharfViktor** [comment]
search by project space name: please skip this step https://github.com/owncloud/ocis/issues/4506

**Comment by SwikritiT** [comment]
@ScharfViktor I found a weird behavior 
1. As user `Einstein` create the following folders
```
      folder       
      new-folder   
      FolDer       
      folderPublic 
      test         
```
2. Now from the global search for `folder`, I get the following result, the test is also included in the search list while it shouldn't be
![Screenshot from 2022-09-05 16-20-52](https://user-images.githubusercontent.com/41103328/188430402-962389da-cd87-4966-bbbd-f6f8c2d44f0c.png)
3. Weirdly I can only reproduce it with a keyword test. 

4. In this I created more folders named `one`, `two`, `three` and when I search for `folder` , `test` is still displayed but not others
![Screenshot from 2022-09-05 16-21-25](https://user-images.githubusercontent.com/41103328/188430577-7d25c722-9862-4291-a4a7-82a974670873.png)
 
The test also fails here for the same reason https://drone.owncloud.com/owncloud/web/28072/12/13 passes in `oc10` though

**Comment by ScharfViktor** [comment]
Yes, I can confirm it.
the first search gives me extra "foo" and "test" folders. Strange, but I don't see request with limit 5
<img width="908" alt="Screenshot 2022-09-05 at 13 38 45" src="https://user-images.githubusercontent.com/84779829/188441121-fd5f0869-3e39-4494-9cfa-70217c9389d5.png">

if I click "search all files". It works correct
<img width="1252" alt="Screenshot 2022-09-05 at 13 39 42" src="https://user-images.githubusercontent.com/84779829/188441285-33988de4-f3e1-470f-8f3c-25d43c67e13d.png">

after that search work correct. If I try to search again
<img width="1274" alt="Screenshot 2022-09-05 at 13 40 29" src="https://user-images.githubusercontent.com/84779829/188441411-4fcc7c43-9d93-4600-ae40-59fbeb9f983c.png">

**Comment by SwikritiT** [comment]
yes weird, after I search in all files the issue is not reproducible at all

**Comment by SwikritiT** [comment]
> yes weird, after I search in all files the issue is not reproducible at all

reproducible after reload, here it gives me all the folders created

![afterreload](https://user-images.githubusercontent.com/41103328/188541031-463eb656-4eda-4982-afed-549e2d227abe.png)

**Comment by SwikritiT** [comment]
I created an issue here https://github.com/owncloud/ocis/issues/4517

**Comment by SwikritiT** [comment]
@ScharfViktor as for `declined` and `pending` share, it is not displayed in the search list, I'm guessing that it's expected behavior. 
Also, searching resources in trashbin doesn't give any result both in `oc10` and `ocis`, is this also expected?

**Comment by SwikritiT** [comment]
created an issue for public link searching https://github.com/owncloud/web/issues/7603

**Comment by SwikritiT** [comment]
> > @ScharfViktor as for `declined` and `pending` share, it is not displayed in the search list, I'm guessing that it's expected behavior. Also, searching resources in trashbin doesn't give any result both in `oc10` and `ocis`, is this also expected?
> 
> I think it it normal behaviors I create api tests for searching `declined` and `pending` share and deleted files. let don't check it in e2e?

okay

**Comment by SwikritiT** [comment]
@ScharfViktor for shares jail is it enough with what is done in PR https://github.com/owncloud/web/pull/7583 or do we need to add more and for `check limit- 5 or more` do you mean character limit by this? I can't find a way to set character limit for global search in ocis, I think we can do that in oc10 through occ command but I need to check first. Do you have any idea if it's possible in ocis or will it ever be?

**Comment by ScharfViktor** [comment]
I think it's enough for e2e tests. We have api tests with limit checking

**Comment by SwikritiT** [comment]
Okay I'll continue on adding steps for `project space` and `public link` after the related issues are fixed

**Comment by SwikritiT** [comment]
@ScharfViktor https://github.com/owncloud/web/issues/7603 this issue has been fixed by https://github.com/owncloud/web/pull/7849 which hides the search bar in the public link. So what do we do about the `search for public (public link)` ?

**Comment by ScharfViktor** [comment]
> @ScharfViktor #7603 this issue has been fixed by #7849 which hides the search bar in the public link. So what do we do about the `search for public (public link)` ?

I think we should remove this case from issue as `cannot be implemented`.  We can probably close the problem because space search by name will not be fixed in the near future.
