### ISSUE TITLE
Check expected-failures files for invalid and closed issues 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/web#7896]
A script is now available to check for invalid and closed issues. https://github.com/owncloud/core/pull/40377

Use it to check the expected-failures files on the web and fix any problems.

In ocis, removing  closed issues done by this issue : [Check expected-failures files for invalid and closed issues](https://github.com/owncloud/ocis/issues/4635)

**Comment by SagarGi** [comment]
### TODO: Issue that has been closed but still in expected to failure for `web` 
- [ ] https://github.com/owncloud/ocis-reva/issues/14
https://github.com/owncloud/web/blob/bc21a26c93494a5c57f7b446472bab5e58b672e3/tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md?plain=1#L3-L4

**Comment by SagarGi** [comment]
This seems to be less priority than other so putting this back to todo for now.

**Comment by SwikritiT** [comment]
> ### TODO: Issue that has been closed but still in expected to failure for `web`
> * [x]  [renaming a resource does not work ocis-reva#14](https://github.com/owncloud/ocis-reva/issues/14) [[tests-only][full-ci]Refactor test steps #8093](https://github.com/owncloud/web/pull/8093)
>   https://github.com/owncloud/web/blob/bc21a26c93494a5c57f7b446472bab5e58b672e3/tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md?plain=1#L3-L4
> * [x]  [user session of a blocked user is not cleared properly #4795](https://github.com/owncloud/web/issues/4795)   Fixed by : [[tests-only][full-ci]Refactor webUILogin/adminBlocksUser.feature:20 to make it follow the current behaviour #8074](https://github.com/owncloud/web/pull/8074)
>   https://github.com/owncloud/web/blob/bc21a26c93494a5c57f7b446472bab5e58b672e3/tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md?plain=1#L11-L12
> * [x]  [Add sorting to files list ocis#1179](https://github.com/owncloud/ocis/issues/1179) [[tests-only][full-ci]Remove tests from expected to failure linked to closed issue #8075](https://github.com/owncloud/web/pull/8075)
>   https://github.com/owncloud/web/blob/bc21a26c93494a5c57f7b446472bab5e58b672e3/tests/acceptance/expected-failures-with-oc10-server-openid-login.md?plain=1#L17-L19
> * [x]  [Scoped links #6844](https://github.com/owncloud/web/issues/6844) [[tests-only][full-ci]Skip private link related tests on ocis #8076](https://github.com/owncloud/web/pull/8076)
>   https://github.com/owncloud/web/blob/ef6006d73f454bab263def916ad6c49a8cbfa565/tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md?plain=1#L36-L38
> * [x]  [Copy/move only works with personal space #6892](https://github.com/owncloud/web/issues/6892) [[tests-only]Skip shares related tests in OCIS #8078](https://github.com/owncloud/web/pull/8078)
>   https://github.com/owncloud/web/blob/ef6006d73f454bab263def916ad6c49a8cbfa565/tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md?plain=1#L138-L140

Alll the issues here have been done. I'll run the script once again to be sure that there aren't anymore closed issues.

**Comment by SwikritiT** [comment]
These issues are closed but is linked on expected to fail
- [ ] [QA] Browser session is valid for newly created user of same name https://github.com/owncloud/ocis/issues/904
https://github.com/owncloud/web/blob/67c641767c4d48e73f69dfd4e4e447f4f28827c2/tests/acceptance/expected-failures-with-oc10-server-openid-login.md?plain=1#L14
https://github.com/owncloud/web/blob/67c641767c4d48e73f69dfd4e4e447f4f28827c2/tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md?plain=1#L79

- [ ] not possible to overwrite a received shared file https://github.com/owncloud/ocis/issues/2267
https://github.com/owncloud/web/blob/67c641767c4d48e73f69dfd4e4e447f4f28827c2/tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md?plain=1#L116

**Comment by SwikritiT** [comment]
Everything in this issue has been merged. Closing this as completed
