### ISSUE TITLE
[e2e]Cleanup users/groups/spaces created by test scenario after execution of tests

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/web#8662]
Currently, we don't clean up users/groups/spaces created by tests at after hook and I think we should implement them.

# TODO
- [x] delete all the users created by tests after execution of each scenario https://github.com/owncloud/web/pull/8998
- [x] delete all the groups created by tests after execution of each scenario https://github.com/owncloud/web/pull/8994
- [x] delete all the spaces created by tests after execution of each scenario https://github.com/owncloud/web/pull/8789

**Comment by SwikritiT** [comment]
# TODO
After the spaces are cleaned up do this https://github.com/owncloud/web/pull/8661#discussion_r1144532986

**Comment by saw-jan** [comment]
PRs done
