### ISSUE TITLE
[share-dialog-redesign] I: Section "Share with people"

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8749]
This is a sub-task of https://github.com/owncloud/web/issues/8743

# Current layout
![grafik](https://user-images.githubusercontent.com/16665512/228586709-0ec59fa0-dbcb-4098-8c9e-6c2828ae26e7.png)

### Problems
- Sidebar title (at least in german) is misleading
- Section title + input label can be improved
- Options (permissions + expiration date) are not recognizable as buttons + down-arrows (carets) are misplaced
- Options (permissions + expiration date) do not have a clear label -> value structure

# Proposal: New layout
![grafik](https://user-images.githubusercontent.com/16665512/228781770-952820ef-a8a5-4bd0-ada2-d0816f8ed057.png)

Sorry for the german screenshot, but most of the raised issues are german based due to gender-neutral wording.

1. Title
Use a title, which is action related. User shares a file, title should read “Share”. 
In german: Current title “Geteilt” is misleading. Use “Teilen” or ”<filename> teilen”

2. Rename section title and label
The section title should clearly separate from the other section title (“Share via link”) and show the difference.
The label should be a describing element to the input field.

3. Sharing options
- Re-structure: Use rows for different options
- Rename permissions (see subtask -enter issue-)
- Permissions: Select lowest permission (`view`) as default
- Expiration date: When selected, show date and remaining time: `expiration date: 1.5.2023 (15 days, 12 hours)`

# Tasks
- [ ] Change texts

| element | current english | new english | current german | new german |
|---------|----------------|-------------|-----------------|-------------|
| Sidebar title | Shares | Share | Geteilt | Teilen |
| section title | Share with people | Share with people | Personen einladen | Mit anderen teilen |
| Input field | Invite | Search for people and groups | Einladen | Personen und Gruppen suchen |

- [ ] Place sharing options in rows
- [ ] Re-Structure sharing options as clear label -> value pairs
- [ ] Move CTA to own row, align right

**Comment by tbsbdr** [comment]
Talked with Markus as not all of the suggestions from him where improvements imo.

I'd suggest the following - what do you think @hurradieweltgehtunter @kulmann ?
## Proposal
![Image](https://user-images.githubusercontent.com/26610733/229129996-518dc658-04dc-4a24-b76a-c38d4d3b3406.png)


## Dismissed ideas ❌

### V2
![Image](https://user-images.githubusercontent.com/26610733/229130671-46137a47-038e-4e45-bc86-2800c5e1f7c0.png)

### V3


![Image](https://user-images.githubusercontent.com/26610733/229130761-ad9d0c79-859e-4eef-ae25-94a60e1e958b.png)

**Comment by hurradieweltgehtunter** [comment]
I like your proposal. But I'm not sure if it works generally without labels ("permission", "Expiration date"), also regarding accessibility. 
Wording for permissions ("can edit" etc) is the best working solution IMO

**Comment by kulmann** [comment]
> I like your proposal. But I'm not sure if it works generally without labels ("permission", "Expiration date"), also regarding accessibility. If it does, 👌
> Wording for permissions ("can edit" etc) is the best working solution IMO

Regarding a11y, that’s what aria-label, aria-describedby and the like are made for. We can make that work easily.
For a form in the usual style (with lots of text inputs etc) it should be done with labels. But for „special input“ it’s fine to use aria props.
