### ISSUE TITLE
[share-dialog-redesign] II: Share via link

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/web#8750]
This is a sub-task of https://github.com/owncloud/web/issues/8743

# Current layout 
![grafik](https://user-images.githubusercontent.com/16665512/228587144-235fd2f2-c16d-4c8a-87f0-d4f83e78edf6.png)

## Problems
- List of available links and create-link-form is mixed (quicklink is above, other available links are below create-link-form)
- Button for creating a link is not recognizable as such
- Options for new links (passord, epxiration date) are hidden 
- Permission on existing links do not have a clear label -> value structure

## Quicklink
One thing I always stumble upon: What purpose does a quicklink serve? 
I could understand it if it would behave like the private link in oc 10: always available, no need to create it, no settings on permissions or anything else. Stress the **Quick** in **Quick**link: Use it quick. For everything else, there are the other sharing options. (see also the chapter above about the “internal” “permission”)

Question: Is it possible to remove all customization options, use it as fixed link and really focus on **quick** ?

# Proposal: New Layout

![grafik](https://user-images.githubusercontent.com/16665512/228794383-86e05a65-2cc0-4b2e-b074-67eaac4d30d6.png)

- Similar structure to "Share with people" ( #8749 ): vertical share options (permissions, expiration date)
- Available links are grouped (including quicklink) while link creation dialog is clearly separated
- Link creation dialog is similar to other "Create" dialogs (Compare "Share with people")
- Get rid of link icons in (fake) input fields on created links as they serve no purpose

# Tasks

- [ ] Clarify Quicklink
- [ ] Set up a clear "Create new link" form with clear CTA
- [ ] Set up a clear overview list for existing links, most current on top
- [ ] Arrange link options (permission, expiration date, password, ...) as vertical list
- [ ] Arrange link options as label -> value pairs
  - Password and expiration date need to be clearable, Permission is not clearable

**Comment by kulmann** [comment]
The internal link doesn't belong in the link section in my opinion. It belongs more close to the shares. I have the feeling that a real improvement will be quite the disruptive change in the UI. But I didn't manage to come up with a good idea, yet.

I thought about auto-creating one internal link per file, putting it near the shares listing (non-editable) and remove the `Internal` role from the other links. Because functionality wise every internal link behaves the same. But that would be such much data-waste - one internal link per file would be just insane. Which would bring us back to the private link, which is not created in the data layer but only exists from a string concatenation.

**Comment by ChrisEdS** [comment]
The possibility to create a password is missing in your proposal?

<img width="456" alt="image" src="https://user-images.githubusercontent.com/33026403/229249630-6d66386a-8dd3-4823-8b76-ecd1380dea81.png">

**Comment by kulmann** [comment]
Share dialog redesign is not on the roadmap. What we currently have works for now. Thanks for the input, maybe later when we come back to this in the future.
