### ISSUE TITLE
[CERN] Buckets for Web Merge

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/web#9278]
# Core

- [x] [De-duplicate event handling to prevent errors on Draw-io](https://github.com/owncloud/web/pull/9159/commits/0a0cd9940a682d2c0c91744ea99e45e533e55f9d)  fixed via https://github.com/owncloud/web/pull/8576
- [x]  [Fix 'Show more'-action in shares panel](https://github.com/owncloud/web/pull/9159/commits/98e47e5bed3e1593000de6826240eab8e3cb61cc) fixed upstream https://github.com/owncloud/web/pull/8482
- [x]  [Fix multiline breadcrumb](https://github.com/owncloud/web/pull/9159/commits/7abee7a63662fc22b74cd12f1606f44408e35f0b) fixed via https://github.com/owncloud/web/pull/8984 https://github.com/owncloud/web/pull/8765
- [x]  [Single file share view](https://github.com/owncloud/web/pull/9159/commits/44f5d2ca0ad63e854bbb80bf9670e4d1cd765afe) fixed via https://github.com/owncloud/web/pull/8446
- [x]  [Option for max length of breadcrumb item](https://github.com/owncloud/web/pull/9159/commits/537e2327cbacb86c2ec5bde91fc139101ed7ae38) superseeded by https://github.com/owncloud/web/pull/8984 https://github.com/owncloud/web/pull/8765
- [x]  [Advanced/collapsible table](https://github.com/owncloud/web/pull/9159/commits/7dc1c55d1d0f794fddade0f649a2526b7064074c) (until oc provides a better concept via filters) in progress: https://github.com/owncloud/web/pull/8443
- [x]  [More file extensions for text-editor](https://github.com/owncloud/web/pull/9159/commits/323030a42bc6184850b8f20f3106e827b6443e63) fixed via https://github.com/owncloud/web/pull/7967
- [x] [Favorites view update on remove from favorites](https://github.com/owncloud/web/pull/9159/commits/a2dcfceeeba1fcb95ccd56ede3058240263e7b64) fixed upstream https://github.com/owncloud/web/pull/9237
- [x]  [Improvements to User search autocomplete listing look and feel](https://github.com/owncloud/web/pull/9159/commits/d04a7ae28a27a0dc5d5e5dc17aa362aeacf14694) fixed upstream https://github.com/owncloud/web/pull/9273
- [x]  [Possibility to open apps in the same tab](https://github.com/owncloud/web/pull/9159/commits/1c4c93d497809967030f5100fa97ce33d41faa55) fixed upstream https://github.com/owncloud/web/issues/6661
- [x] [Archiver in password protected links](https://github.com/owncloud/web/pull/9159/commits/889bd008fa47c56dfb05ad43f63b2365e23689fd) fixed upstream https://github.com/owncloud/web/pull/6471
- [x] [Scroll to new folder on creation](https://github.com/owncloud/web/pull/9159/commits/b6e42b6aba5a8cddd5cbe220b29bbb558b8d2205) in progress #7600  #9145
- [x] #7601
- [x]  [Only use access token if not public token](https://github.com/owncloud/web/pull/9159/commits/a5b171726f9a0e123bb05aad175e3b493aebba68)  in progress https://github.com/owncloud/web/issues/9296 
- [x]  [Show error message on failing upload](https://github.com/owncloud/web/pull/9159/commits/e1e06aa508e621ddbd3f6bbd5066e125dff135e4) fixed upstream #9076
- [x]  [Fix quota percentage](https://github.com/owncloud/web/pull/9159/commits/f972d1dfcb7e18737033c091bee3816045f6b4a5) #9259 #9369
- [x]  [App open bar on header](https://github.com/owncloud/web/pull/9159/commits/31e2ad66bfa301a145b4c14c0c77080c742f8618) work in progress via #8447 
- [x] [Warning of disabled popups by window.open actions](https://github.com/owncloud/web/pull/9159/commits/4ba7a443104df9a62f73905e578873cbe464bb3c) via #9377
- [x]  [Auth redirection workaround](https://github.com/owncloud/web/pull/9159/commits/e1630d9603a446280e2c745d32babe6a2cddbad2) issue for upstream solution: https://github.com/owncloud/web/issues/9261 PR: https://github.com/owncloud/web/pull/9364
- [x]  [Prevent tokeninfo request](https://github.com/owncloud/web/pull/9159/commits/7d70c676cddc746ce3917b0bf168ff348fa2eaa7)  replace via buildtime-flag https://github.com/owncloud/web/issues/9310
 - [x]  [Automatically open single file share app](https://github.com/owncloud/web/pull/9159/commits/b29df6470ef943dd99807793412e188a80f1b973) via  https://github.com/owncloud/web/issues/9045
- [x]  [Fix crash on bad egroups](https://github.com/owncloud/web/pull/9159/commits/808848f25a51f5af7fe251aea616d5e2f06ab710) via https://github.com/owncloud/web/issues/9257
- [x]  [New notifications system](https://github.com/owncloud/web/pull/9159/commits/9ffff2de54266f231e43e1e7e96e8110ae0ea7a5) enable via feature flag upstream;  via #9378

## Waiting for backend changes
- [x] [Sharing UI improvements](https://github.com/owncloud/web/pull/9159/commits/11ad6f411858cf00dff427c6c0e3952b3c05a66e) via https://github.com/owncloud/web/issues/9376
- [x]  [Change UI language](https://github.com/owncloud/web/pull/9159/commits/89949c33aaa53778735529deb296e6248f4d13e4) https://github.com/owncloud/web/issues/9243
- [x]  [Clean urls and spaces mock](https://github.com/owncloud/web/pull/9159/commits/6b774f2dfad7f8097b80539db30cfa27a355d299) List Projects requires the backend to implement additional APIs via https://github.com/owncloud/web/issues/9229  https://github.com/owncloud/web/issues/9308 and https://github.com/owncloud/web/issues/9865
- [x] [Disable actions on certain paths](https://github.com/owncloud/web/pull/9159/commits/1563e15a2a051833718eb4a662b3525e3f996278) needs a solution to prohibit download/copy, ideally on permission level (there is no such permission yet!) so that the backend can just omit that permission in the webdav permissions. The write actions (e.g. delete) belong into the "rejected" bucket, have to be solved via webdav permissions backend side.  https://github.com/owncloud/web/issues/9218
- [x]  [Enable router-history-mode](https://github.com/owncloud/web/pull/9159/commits/d08394206a1a025be772d17892cea87b9874e317) provide via buildtime html header partial (see this issue) via https://github.com/owncloud/web/issues/9382
- [x]  [Shared with me/others/links views](https://github.com/owncloud/web/pull/9159/commits/49e125f81c023e1c71d772d72b346a1cc0ac3f35) should just fall into place when share urls are done. via https://github.com/owncloud/web/issues/9379

# Extension system -> @dschmidt
- [x]  [Federated and lightweight accounts](https://github.com/owncloud/web/pull/9159/commits/9c4ec26e770d914b34a8e16270f51906a9fa09ea) needs custom view to welcome light users;  via https://github.com/owncloud/web/issues/9381
- [x] [Search on current folder](https://github.com/owncloud/web/pull/9159/commits/f22428c83d36b966654a78cf51d16dcf3401f37f) via https://github.com/owncloud/web/issues/9264
- [x] [Cephfs link in navbar](https://github.com/owncloud/web/pull/9159/commits/d5d936c9ca993a187f8d5a9a66c4b838c0e9eb8f) via https://github.com/owncloud/web/issues/9239
- [x]  [Clean urls and spaces mock](https://github.com/owncloud/web/pull/9159/commits/6b774f2dfad7f8097b80539db30cfa27a355d299) Requesting projects via Button via extension via https://github.com/owncloud/web/issues/9228
- [x]  [OCM app](https://github.com/owncloud/web/pull/9159/commits/369a99fd65f415a68e3b76c840a334bcc7938c5b) How do we setup a development instance of sciencemesh? via https://github.com/owncloud/web/issues/9268
- [x]  [Backups app](https://github.com/owncloud/web/pull/9159/commits/27146023f4ca5793a16e16382b353aaf67bb37d4) via https://github.com/owncloud/web/issues/9267 https://github.com/cernbox/web-extensions/pull/21
- [x]  [Use reva token for auth](https://github.com/owncloud/web/pull/9159/commits/9c37d8cfa80a7fd3dafc50e14df8647ea1cf3680) post login hook via extension system https://github.com/owncloud/web/issues/9245#issuecomment-1592883946
- [x]  [Read only view mode default for shares of MS Office apps](https://github.com/owncloud/web/pull/9159/commits/2894f0cbe9a2c3515be87eb9fb4ed679f52e400a) via https://github.com/owncloud/web/issues/9255

# Rejected

- [Pass access token as query if signed URLs are not supported](https://github.com/owncloud/web/pull/9159/commits/8df4ea4fbbf70eb7dcd30afcc581332614a4de7a)
- [Handle old apps url](https://github.com/owncloud/web/pull/9159/commits/70499dc23bff7a06a342dc68f8a1edd09e031c49) @diocas wanted to evaluate if custom JS is sufficient. needs documentation how to inject js @pascalwengerter  ; should be documented https://github.com/owncloud/web/pull/8432 
- [Notifications of outages](https://github.com/owncloud/web/pull/9159/commits/a1f92acdb8131eb2219c07e2b0b2f4973fd12409) needs some extra styling, eliza will provide is as an extension
- [Ignore re-sharable](https://github.com/owncloud/web/pull/9159/commits/7469130838286f457f0430eafdd6398a5e232408) will be done in the backend https://github.com/owncloud/web/issues/9262#issuecomment-1598668992

**Comment by tbsbdr** [comment]
@kulmann if you have the chance - could you have a look at the current bucket assignments and re-bucket according to your oppinion?

**Comment by kulmann** [comment]
I moved 10. into core because we need to find a solution for revoking the download/copy permission (which is not a webdav permission yet). The rest of the commit has to be done by changing webdav permissions backend side (so you could call that "rejected").

The share views commit (31) belongs into the core bucket, because that should be done already when we have the new share urls. Which is not listed here, but also belongs into core.

The rest looks adequate to me. Thank you Tobi! 👌🏼

**Comment by labkode** [comment]
> * [Enable router-history-mode](https://github.com/owncloud/web/pull/9159/commits/d08394206a1a025be772d17892cea87b9874e317) should be configured via the webserver / baseurl;

Regarding this one, I did a bit of R&D on OCIS and I found the following:

https://github.com/owncloud/ocis/blob/master/services/web/pkg/assets/server.go#L26
https://github.com/owncloud/ocis/blob/master/services/web/pkg/assets/server.go#L52
https://github.com/owncloud/ocis/blob/master/services/web/pkg/assets/server.go#L65

Basically OCIS is doing what Diogo implemented in the Web PR.

Now the question is: where this responsibility should be stored? 

My take is Web for two reasons:
i) the change concerns the behaviour of the Web, and for me makes sense to control that change in the Web repo
ii) I would have provided a config option to OCIS that when building it, you can pass the baseURL as a configuration option when embedding the Web assets

The current approach means the same logic needs to be implemented  in OC10, OCIS and Reva@master, while you could have it only in Web.

**Comment by kulmann** [comment]
Diogos commit achieves the same, but via build config. Since web gets embedded into ocis as a generic asset, build config didn't make sense for the product. Otherwise any deployment of ocis would need to rebuild the web assets to cook the base url into the assets.

**Comment by labkode** [comment]
@kulmann in that case, I suggest to take Diogo's PR and change it to provide the default that OCIS does, baseURL is always `/`. With that change, we do not provide a build option, and in case someone wants to change that, they can do what OCIS was doing until now. Would that be acceptable? 

That will remove the following logic from OCIS:
```
https://github.com/owncloud/ocis/blob/master/services/web/pkg/assets/server.go#L52
https://github.com/owncloud/ocis/blob/master/services/web/pkg/assets/server.go#L65
```

**Comment by dschmidt** [comment]
What exactly is your suggestion?

Add `<base href="/"/></head>` everywhere and have ocis rewrite it instead of adding it completely dynamically?

I don't think adding `data.buildConfig.baseUrl` is necessary for the `manifest.json` or any of the script tags if the `base` tag is just added at the top of `<head>`, so there's basically nothing else left in that commit (except for the `vite.config.ts` change which is fine with me).

**Comment by labkode** [comment]
@dschmidt OCIS only adds dynamically `<base href="/"/></head>` on these 3 files:

https://github.com/owncloud/ocis/blob/master/services/web/pkg/assets/server.go#L49
```
case "index.html", "oidc-callback.html", "oidc-silent-redirect.html"
```


> I don't think adding `data.buildConfig.baseUrl` is necessary for the `manifest.json` or any of the script tags if the `base` tag is just added at the top of `<head>`, so there's basically nothing else left in that commit (except for the `vite.config.ts` change which is fine with me).

That is what I meant by `we do not provide a build option`.

The only part left of that PR is the fact of adding the `<base href="/"/></head>` part to the above mentioned HTML pages  (adding them to all of them as part of an included template won't hurt neither).

The `vite.config.ts` (I have no idea what is about), up to you.

**Comment by kulmann** [comment]
I don't remember the details but I think we can't enforce the history mode as the webserver needs some config as well. Only the hash mode works out of the box. Since web is also supporting oc10 as backend we cannot enforce the history mode in web.

**Comment by dschmidt** [comment]
Backups App PR sent: https://github.com/cernbox/web-extensions/pull/21

**Comment by tbsbdr** [comment]
assigned https://github.com/owncloud/web/pull/9159/commits/9ffff2de54266f231e43e1e7e96e8110ae0ea7a5 to core bucket CC @dschmidt @elizavetaRa @diocas @kulmann . I'd love to have this feature generally available in the product in a different way, but considering time/ETA, we need to proceed via feature-flag option.
