### ISSUE TITLE
Remove owncloud-sdk and re-implement it in web-client

### ISSUE THREAD

**Issue by JammingBen** [owncloud/web#9709]
The `owncloud-sdk` is quite old, does not fullfil our code standards and is hard to maintain because of the linking process. The latter makes future adjustments very time consuming, especially since we're planning to switch to id-based WebDAV requests.

 Hence we figured it makes sense to remove the `owncloud-sdk` and implement its logic in our `web-client` package.

#### To-Do's

- [x] Make sure Web uses the provided `webdav` abstraction instead of the sdk directly for webdav requests
- [x] Port all WebDAV requests to a new abstraction in `web-client`
- [x] Port OCS requests to a new abstraction in `web-client` (expect for the sharing stuff, which will be replace via sharing NG)
- [x] Check if settings API needs to be ported -> no needed
- [x] What about `signUrl` logic? -> https://github.com/owncloud/web/pull/10621
- [x] Add proper (unit-) tests for the new code

**Comment by kulmann** [comment]
Hopefully pays off now that @dschmidt and myself already built an abstraction layer for webdav in web-client. 🙈
